<?php
if($session_gender=="Male")
        {
            $session_He="He";
            $session_he="he";
            $session_His="His";
            $session_his="his";
        }
        elseif($session_gender=="Female")
        {
            $session_He="She";
            $session_he="her";
            $session_His="Her";
            $session_his="her";
        }
        else
        {
            $session_He="It";
            $session_he="it";
            $session_His="Its";
            $session_his="its";
        }
?>